# Generated by Django 4.0.4 on 2022-04-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(null=True, verbose_name='ادرس مقاله')),
                ('descirption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('content', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='عکس')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('massege', models.TextField(verbose_name='نظر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
