# Generated by Django 4.0.4 on 2022-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('time', models.TimeField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
