# Generated by Django 4.0.4 on 2022-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0002_food_delete_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان لازم'),
        ),
    ]
