# Generated by Django 4.0.4 on 2022-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0003_alter_food_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('all', 'همه'), ('pitza', 'پیتزا'), ('sandwich', 'ساندویچ'), ('dessert', 'دسر')], default='all', max_length=10, verbose_name='دسته بندی غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
