# Generated by Django 4.0.4 on 2022-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0004_food_type_food_alter_food_pub_date_alter_food_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('pitza', 'پیتزا'), ('sandwich', 'ساندویچ'), ('dessert', 'دسر'), ('all', 'همه')], default='all', max_length=10, verbose_name='دسته بندی غذا'),
        ),
    ]
