# Generated by Django 4.0.4 on 2022-04-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0005_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'لیست غذا', 'verbose_name_plural': 'لیست غذا ها'},
        ),
    ]
