# Generated by Django 4.0.4 on 2022-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0007_chefs_food_chef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'سرآشپز', 'verbose_name_plural': 'سرآشپز ها'},
        ),
    ]
