# Generated by Django 4.0.4 on 2022-04-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0008_alter_chefs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(verbose_name='ادرس دسته بندی')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
