# Generated by Django 4.0.4 on 2022-05-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoods', '0010_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='myfoods.category', verbose_name='دسته بندی'),
        ),
    ]
