# Generated by Django 4.0.4 on 2022-04-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'لیست رزرو ', 'verbose_name_plural': 'لیست رزرو ها'},
        ),
    ]
